package com.taskflowpro.entity;

public enum EventType {
  USER_SIGNED_IN,
  WORKSPACE_CREATED,
  MEMBER_ADDED,
  MEMBER_INVITED,
  MEMBER_JOINED,
  MEMBER_ROLE_CHANGED,
  MEMBER_REMOVED,
  MEMBER_INVITATION_CANCELLED,
  PROJECT_CREATED,
  PROJECT_UPDATED,
  TASK_CREATED,
  TASK_ASSIGNED,
  TASK_STATUS_CHANGED,
  TASK_PRIORITY_CHANGED,
  COMMENT_ADDED
}
